resolver: lts-8.2
extra-deps:
- web-inv-route-0.1.1
packages:
- location: rpc
- location: nfs
- location: webdav
- location:
    git: git://github.com/dylex/invertible
    commit: 0.2.0
  subdirs:
  - .
  - hxt
  - conduit
  extra-dep: true
- location:
    git: git://github.com/dylex/waimwork
    commit: master
  extra-dep: true
flags:
  web-inv-route:
    snap: false
    happstack: false
explicit-setup-deps:
  nfs: true
ghc-options:
  ONC-RPC: -Wall -Werror
  nfs: -Wall -Werror
  webdav-nfs: -Wall -Werror
